const CartActionTypes = {
  ADD_PRODUCT_TO_CART: "ADD_PRODUCT_TO_CART",
  REMOVE_PRODUCT_FROM_CART: "REMOVE_PRODUCT_FROM_CART",
  DECREASE_QTY_PRODUCT_FROM_CART: "DECREASE_QTY_PRODUCT_FROM_CART",
  EMPTY_CART: "EMPTY_CART",
};

export default CartActionTypes;
