const ReviewsActionTypes = {
  ADD_REVIEW_TO_DB: "ADD_REVIEW_TO_DB",
  REVIEW_ADD_SUCCESS: "REVIEW_ADD_SUCCESS",
  REVIEW_ADD_FAILURE: "REVIEW_ADD_FAILURE",
  FETCH_REVIEWS_FROM_DB: "FETCH_REVIEWS_FROM_DB",
  FETCH_REVIEWS_SUCCESS: "FETCH_REVIEWS_SUCCESS",
  FETCH_REVIEWS_FAILURE: "FETCH_REVIEWS_FAILURE",
};

export default ReviewsActionTypes;
