const CheckoutActionTypes = {
  CHECKOUT_PROCESS_START: "CHECKOUT_PROCESS_START",
  CHECKOUT_PROCESS_SUCCESS: "CHECKOUT_PROCESS_SUCCESS",
  CHECKOUT_PROCESS_FAIL: "CHECKOUT_PROCESS_FAIL",
  CHECKOUT_PROCESS_CANCEL: "CHECKOUT_PROCESS_CANCEL",
  SET_CHECKOUT_PERSONAL_INFO: "SET_CHECKOUT_PERSONAL_INFO",
  SET_CHECKOUT_SHIPMENT_INFO: "SET_CHECKOUT_SHIPMENT_INFO",
};

export default CheckoutActionTypes;
