const ProductsActionTypes = {
  FETCH_DATA_START: "FETCH_DATA_START",
  FETCH_DATA_START_ASYNC: "FETCH_DATA_START_ASYNC",
  FETCH_DATA_SUCCESS: "FETCH_DATA_SUCCESS",
  FETCH_DATA_FAILURE: "FETCH_DATA_FAILURE",
};

export default ProductsActionTypes;
