const UserActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_WITH_GOOGLE: "SIGN_IN_WITH_GOOGLE",
  SIGN_IN_WITH_EMAIL: "SIGN_IN_WITH_EMAIL",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE,",
  IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
  LOGOUT_USER: "LOGOUT_USER",
  LOGOUT_USER_SUCCESS: "LOGOUT_USER_SUCCESS",
  SET_USER_CHECKOUT_PERSONAL_INFO: "SET_USER_CHECKOUT_PERSONAL_INFO",
  SET_USER_CHECKOUT_SPEDITION_INFO: "SET_USER_CHECKOUT_SPEDITION_INFO",
};

export default UserActionTypes;
