const UsersActionTypes = {
  SET_CURRENT_USER: "SET_CURRENT_USER",
  SIGN_IN_WITH_GOOGLE: "SIGN_IN_WITH_GOOGLE",
  SIGN_IN_WITH_EMAIL: "SIGN_IN_WITH_EMAIL",
  SIGN_IN_SUCCESS: "SIGN_IN_SUCCESS",
  SIGN_IN_FAILURE: "SIGN_IN_FAILURE",
  SIGN_UP_START: "SIGN_UP_START",
  SIGN_UP_SUCCESS: "SIGN_UP_SUCCESS",
  SIGN_UP_FAILURE: "SIGN_UP_FAILURE,",
  IS_USER_LOGGED_IN: "IS_USER_LOGGED_IN",
};

export default UsersActionTypes;
